name: Terraform Format, Lint, and Check

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  tfFormatValidate:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        continue-on-error: true 
        run: terraform fmt -check -recursive || (echo "Terraform fmt required for the following files:" && terraform fmt -diff -recursive && exit 1)

      - name: Terraform Validate
        if: always()
        run: terraform validate

  tfPlanNetworking:
    name: Terraform Plan
    uses: ./.github/workflows/tf-plan.yml
    needs: [tfFormatValidate]
    secrets: inherit
    with:
      ENVIRONMENT: networking
      AWS_DEFAULT_REGION: ap-southeast-2

  tfPlanApplication:
    name: Terraform Plan
    uses: ./.github/workflows/tf-plan.yml
    needs: [tfFormatValidate]
    secrets: inherit
    with:
      ENVIRONMENT: application
      AWS_DEFAULT_REGION: ap-southeast-2